version: '2.1'
services:
  wiki:
    image: simplyintricate/mediawiki:1.28
    #build:
    #  context: build/wiki
    depends_on:
      - db
    ports:
      - "8123:80"
    volumes:
      - ${PWD}/build/wiki/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/build/wiki/LocalSettings.php:/usr/share/nginx/html/LocalSettings.php:ro
      - ${PWD}/build/wiki/LocalSettings_ffa_re_pnp.php:/usr/share/nginx/html/LocalSettings_ffa_re_pnp:ro
      - ${PWD}/build/wiki/logo-ffa-re.png:/usr/share/nginx/html/resources/assets/logo-ffa-re.png:ro
      - /data/ffa-wiki-family/images/:/usr/share/nginx/html/images
      - /data/ffa-wiki-family/extensions/:/tmp/extensions

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - /data/ffa-wikis-db
