version: '2.1'
services:
  wiki:
    #image: simplyintricate/mediawiki:1.28
    build:
      context: build/wiki
    depends_on:
      initdb:
        condition: service_healthy
    volumes:
      - /data/ffa-wiki-family/images/:/usr/share/nginx/html/images
      - /data/ffa-wiki-family/extensions/:/tmp/extensions
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - SMTP_HOST=smtp.server.com
      - SMTP_PORT=8888
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
      - NGINX_HOST=123.123.123.123
      # NGINX_PORT should be the same as the published port, below, or 80 by default
      - NGINX_PORT=80
      # Mediawiki secret: https://www.mediawiki.org/wiki/Manual:$wgSecretKey
      - MW_SECRET=abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz01
    #ports:
      # should be compatible with NGINX_PORT above
      #- "8001:8001"

  db:
    #image: mysql:8
    build:
      context: build/db
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - /data/ffa-wiki-family/db:/var/lib/mysql

  initdb:
    #image: mysql:8
    build:
      context: build/initdb
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    depends_on:
      db:
        condition: service_healthy
