version: '2.1'
services:
  wiki:
    #image: simplyintricate/mediawiki:1.28
    build:
      context: build/wiki
    depends_on:
      initdb:
        condition: service_healthy
    volumes:
      - /data/ffa-wiki-family/images/:/usr/share/nginx/html/images
      - /data/ffa-wiki-family/extensions/:/tmp/extensions
    ports:
      # update nginx config in build/wiki/default.conf with this port
      - "8001:8001"

  db:
    #image: mysql:8
    build:
      context: build/db
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - /data/ffa-wikis-db

  initdb:
    #image: mysql:8
    build:
      context: build/initdb
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    depends_on:
      db:
        condition: service_healthy
