version: '2.1'
services:
  wiki:
    image: simplyintricate/mediawiki:1.28
    #build:
    #  context: build/wiki
    depends_on:
      initdb:
        condition: service_healthy
    volumes:
      - ${PWD}/build/wiki/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/build/wiki/LocalSettings.php:/usr/share/nginx/html/LocalSettings.php:ro
      - ${PWD}/build/wiki/LocalSettings_ffa_re_pnp.php:/usr/share/nginx/html/LocalSettings_ffa_re_pnp.php:ro
      - ${PWD}/build/wiki/LocalSettings_ffa_pb_pnp.php:/usr/share/nginx/html/LocalSettings_ffa_pb_pnp.php:ro
      - ${PWD}/build/wiki/logo-ffa-re.png:/usr/share/nginx/html/resources/assets/logo-ffa-re.png:ro
      - ${PWD}/build/wiki/logo-ffa-pb.gif:/usr/share/nginx/html/resources/assets/logo-ffa-pb.gif:ro
      - /data/ffa-wiki-family/images/:/usr/share/nginx/html/images
      - /data/ffa-wiki-family/extensions/:/tmp/extensions
      - ${PWD}/build/wiki/wiki-family-entrance-index.html:/usr/share/nginx/html/wiki-family-entrance/index.html:ro
    ports:
      # update nginx config in build/wiki/default.conf with this port
      - "8001:8001"

  db:
    #image: mysql:8
    build:
      context: build/db
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - /data/ffa-wikis-db

  initdb:
    #image: mysql:8
    build:
      context: build/initdb
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    depends_on:
      db:
        condition: service_healthy
