version: '2.1'
services:
  wiki:
    #image: simplyintricate/mediawiki:1.28
    build:
      context: build/wiki
    depends_on:
      initdb:
        condition: service_healthy
    volumes:
      - /data/docker-wiki-family/images/:/usr/share/nginx/html/images
      - /data/docker-wiki-family/extensions/:/tmp/extensions
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - SMTP_HOST=smtp.server.com
      - SMTP_PORT=8888
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
      - NGINX_HOST=123.123.123.123
      # NGINX_PORT should be the same as the left-hand side
      # of published port, below, or 80 by default
      - NGINX_PORT=8001
      # Mediawiki secret: https://www.mediawiki.org/wiki/Manual:$wgSecretKey
      - MW_SECRET=abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz01
    #ports:
      # Left-hand side should be compatible with NGINX_PORT above
      # Right-hand side should stay "80"
      #- "8001:80"

  db:
    #image: mysql:8
    build:
      context: build/db
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    #volumes:
    #  - /path/to/local/db:/var/lib/mysql

  initdb:
    #image: mysql:8
    build:
      context: build/initdb
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    depends_on:
      db:
        condition: service_healthy

  bkpdb:
    # https://github.com/fradelg/docker-mysql-cron-backup/
    image: fradelg/mysql-cron-backup:latest
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=admin
      - MYSQL_PASS=password
      - INIT_BACKUP=true
      # weekly backup
      - CRON_TIME=0 0 * * 1
    #volumes:
    #  - /path/to/backup:/backup
